"""update schema

Revision ID: 1642ada04603
Revises: a9520a44d7fa
Create Date: 2026-01-30 20:17:45.242572

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1642ada04603"
down_revision: Union[str, Sequence[str], None] = "a9520a44d7fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activity", "parent_activity_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.drop_column("activity", "is_primary")
    op.alter_column(
        "organizations",
        "phone_numbers",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organizations",
        "phone_numbers",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        nullable=True,
    )
    op.add_column(
        "activity",
        sa.Column("is_primary", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "activity", "parent_activity_id", existing_type=sa.BIGINT(), nullable=True
    )
