"""init

Revision ID: a9520a44d7fa
Revises:
Create Date: 2026-01-13 20:13:01.922209

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9520a44d7fa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("parent_activity_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_activity_id"],
            ["activity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "buildings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_buildings_location",
        "buildings",
        ["location"],
        unique=False,
        postgresql_using="gist",
        if_not_exists=True,
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("phone_numbers", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("building_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_org_building", "organizations", ["building_id"], unique=False)
    op.create_index(
        "idx_org_name_hash",
        "organizations",
        ["name"],
        unique=False,
        postgresql_using="hash",
    )
    op.create_table(
        "org_x_activities",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column("activity_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activity.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "activity_id", name="uq_org_activity"),
    )
    op.create_index(
        "idx_org_x_activities_activity_id",
        "org_x_activities",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        "idx_org_x_activities_org_id", "org_x_activities", ["org_id"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_org_x_activities_org_id", table_name="org_x_activities")
    op.drop_index("idx_org_x_activities_activity_id", table_name="org_x_activities")
    op.drop_table("org_x_activities")
    op.drop_index(
        "idx_org_name_hash", table_name="organizations", postgresql_using="hash"
    )
    op.drop_index("idx_org_building", table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(
        "idx_buildings_location", table_name="buildings", postgresql_using="gist"
    )
    op.drop_table("buildings")
    op.drop_table("activity")
    # ### end Alembic commands ###
