"""make parent activity nullable

Revision ID: b1d78b56f193
Revises: 1642ada04603
Create Date: 2026-01-30 20:20:30.445161

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1d78b56f193"
down_revision: Union[str, Sequence[str], None] = "1642ada04603"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activity", "parent_activity_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activity", "parent_activity_id", existing_type=sa.BIGINT(), nullable=False
    )
    # ### end Alembic commands ###
